### ISSUE TITLE
[BUG] Grave that contains folder is not properly buried

### ISSUE THREAD

**Issue by celediel** [BetaPictoris/graveyard#9]
## Describe the bug
A grave that contains folders, once buried, cannot be exhumed. The morgue remains empty. Debug logs show that the files are not even archived properly.

## Expected behavior
Files being extracted correctly, maintaining filesystem layout.

## Logs
[Logs](https://bin.burning.moe/Sjafeb)

## Additional context
It appears that files are not being archived recursively, and the archiving stops at the first folder encountered.

**Comment by BetaPictoris** [comment]
Thanks for the fix and discovering the bug!
